@startuml API Filter Use Case Diagram
title API Filter Use Case Diagram

actor User

rectangle Surge_Filter{
    'Surge3
    User --> (Filter SurgeList)
    User --> (Filter SurgeConfg)
    (Filter SurgeConfg) ..> (Filter SurgeList): <<extend>>
    (Filter SurgeConfg) ..> (Filter Sruge Proxy): <<include>>
}

rectangle SS/SSR_Filter{
    'Shadowsocks
    User --> (Filter Shadowsocks)
    (Filter Shadowsocks) ..> (Decode SS Base64): <<include>>
    (Decode SS Base64) ..> (Decode SS/SSR Base64): <<extend>>

    'ShadowsocksR
    User --> (Filter ShadowsocksR)
    (Filter ShadowsocksR) ..> (Decode SSR Base64): <<include>>
    (Decode SSR Base64) ..> (Decode SS/SSR Base64): <<extend>>
}
@enduml